language: ruby
rvm:
- 2.4.2
- 2.3.0
services:
  - postgresql
before_script:
  - psql -c 'create database gakkou_test;' -U postgres
  - bundle exec rake db:create --all
  - bundle exec rake db:migrate
script:
  -  bundle exec rspec
